name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in 60 days and has been marked as stale, it will not be closed.'
        stale-pr-message: 'This pull request has had no activity in 60 days and has been marked as stale, it will not be closed.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60
        days-before-close: -1
        exempt-issue-labels: 'awaiting-approval,work-in-progress'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
